# Generated by Django 3.2.4 on 2021-07-07 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Threader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
